### ISSUE TITLE
Design Docs Review (MVP & Schema)

### ISSUE THREAD

**Issue by rlim92** [NJanaro/Fit-Follower#1]
Hey Nick! Looking solid so far. Some suggestions below:

**MVP**
- [x] `Users will be able to upload workout data as a json object (upload data from other fitness apps)` lets make this a bonus feature for now. For now we can focus on entering data from a website. 
- [x] Small thing, but should be `logged in users` for `Saving Workouts`

**Schema**
- [x] for `routes` table there is `route_name` twice, remove the ladder one
- [x] for `routes` table there can be more columns, consider adding `description`, `activity`, `distance`
- [x] for `workouts` `duration` is spelled wrong

**Comment by NJanaro** [comment]
Thanks Rich!,

yeah, totally meant to put *bonus* on that json upload feature, must have
forgot.

I will work on these changes before moving on to the next design doc stage
to keep things current.
