### ISSUE TITLE
Design Docs (Sample State, Backend/Frontend Routes)

### ISSUE THREAD

**Issue by rlim92** [NJanaro/Fit-Follower#2]
Hey Nick! Design docs looking good. Some suggestions below: 

**Sample State**
- [x] `user_id` `workout_name` `route_name` should all be camelCased (everything should be) 
- [x] add the new columns you added to your `workouts` and `routes` table as key value pairs to your respective slices of state
- [x] `duration` is spelled wrong 

**Backend Routes**
- Looks great, good job!
- [x] one small thing is you could nest both routes and workouts under users, but its your choice

**Frontend Routes**
- [x] consider adding a `/feed` that grabs some collection of workouts for a user (bonus)

**Comment by NJanaro** [comment]
Good idea with the nesting the routes for workouts and routes. I'm pretty sure I did it correctly, let me know if I messed up somewhere.

The Frontend Routes /feed that you recommended I think is covered in my /dashboard Route with the FeedIndex being probably the most important component there. 

Let me know if I misunderstood any of that. Thanks!
